/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AccountStatusEnum = 'Disabled' | 'UnderReview' | 'NeverSignedIn' | 'Active';

export const AccountStatusEnum = {
    Disabled: 'Disabled' as AccountStatusEnum,
    UnderReview: 'UnderReview' as AccountStatusEnum,
    NeverSignedIn: 'NeverSignedIn' as AccountStatusEnum,
    Active: 'Active' as AccountStatusEnum
};

