/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccessLevel } from './accessLevel';


/**
 * ApiKey info
 */
export interface ApiKey { 
    /**
     * Access level or permission to be assigned to this ApiKey.
     */
    AccessLevel?: Array<AccessLevel>;
    /**
     * Name of the ApiKey.
     */
    Name?: string;
    /**
     * Date this ApiKey was created.
     */
    DateCreated?: string;
    /**
     * Date this ApiKey was last used.
     */
    LastUse?: string | null;
    /**
     * Date this ApiKey expires.
     */
    Expires?: string | null;
    /**
     * Which IPs can use this ApiKey
     */
    RestrictAccessToIPRange?: Array<string>;
}

