/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of body part
 */
export type BodyContentType = 'HTML' | 'PlainText' | 'AMP' | 'CSS';

export const BodyContentType = {
    Html: 'HTML' as BodyContentType,
    PlainText: 'PlainText' as BodyContentType,
    Amp: 'AMP' as BodyContentType,
    Css: 'CSS' as BodyContentType
};

