/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeliveryOptimizationType } from './deliveryOptimizationType';
import { SplitOptions } from './splitOptions';


/**
 * Different send options for a Campaign
 */
export interface CampaignOptions { 
    DeliveryOptimization?: DeliveryOptimizationType;
    /**
     * Should the opens be tracked? If no value has been provided, Account\'s default setting will be used.
     */
    TrackOpens?: boolean | null;
    /**
     * Should the clicks be tracked? If no value has been provided, Account\'s default setting will be used.
     */
    TrackClicks?: boolean | null;
    /**
     * Date when this Campaign is scheduled to be sent on
     */
    ScheduleFor?: string | null;
    /**
     * How often (in minutes) to send the campaign
     */
    TriggerFrequency?: number;
    /**
     * How many times send the campaign
     */
    TriggerCount?: number;
    SplitOptions?: SplitOptions;
}
export namespace CampaignOptions {
}


