/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * FileResponse compression format
 */
export type CompressionFormat = 'None' | 'Zip';

export const CompressionFormat = {
    None: 'None' as CompressionFormat,
    Zip: 'Zip' as CompressionFormat
};

