/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ContactSource = 'DeliveryApi' | 'ManualInput' | 'FileUpload' | 'WebForm' | 'ContactApi' | 'VerificationApi' | 'FileVerificationApi' | 'PilotBillingPlan' | 'PaidNewsletter';

export const ContactSource = {
    DeliveryApi: 'DeliveryApi' as ContactSource,
    ManualInput: 'ManualInput' as ContactSource,
    FileUpload: 'FileUpload' as ContactSource,
    WebForm: 'WebForm' as ContactSource,
    ContactApi: 'ContactApi' as ContactSource,
    VerificationApi: 'VerificationApi' as ContactSource,
    FileVerificationApi: 'FileVerificationApi' as ContactSource,
    PilotBillingPlan: 'PilotBillingPlan' as ContactSource,
    PaidNewsletter: 'PaidNewsletter' as ContactSource
};

