/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContactActivity { 
    /**
     * Total emails sent.
     */
    TotalSent?: number;
    /**
     * Total emails opened.
     */
    TotalOpened?: number;
    /**
     * Total emails clicked
     */
    TotalClicked?: number;
    /**
     * Total emails failed.
     */
    TotalFailed?: number;
    /**
     * Last date when an email was sent to this contact
     */
    LastSent?: string | null;
    /**
     * Date this contact last opened an email
     */
    LastOpened?: string | null;
    /**
     * Date this contact last clicked an email
     */
    LastClicked?: string | null;
    /**
     * Last date when an email sent to this contact bounced
     */
    LastFailed?: string | null;
    /**
     * IP from which this contact opened or clicked their email last time
     */
    LastIP?: string;
    /**
     * Last RFC Error code if any occurred
     */
    ErrorCode?: number | null;
    /**
     * Last RFC error message if any occurred
     */
    FriendlyErrorMessage?: string;
}

