/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ContactStatus = 'Transactional' | 'Engaged' | 'Active' | 'Bounced' | 'Unsubscribed' | 'Abuse' | 'Inactive' | 'Stale' | 'NotConfirmed';

export const ContactStatus = {
    Transactional: 'Transactional' as ContactStatus,
    Engaged: 'Engaged' as ContactStatus,
    Active: 'Active' as ContactStatus,
    Bounced: 'Bounced' as ContactStatus,
    Unsubscribed: 'Unsubscribed' as ContactStatus,
    Abuse: 'Abuse' as ContactStatus,
    Inactive: 'Inactive' as ContactStatus,
    Stale: 'Stale' as ContactStatus,
    NotConfirmed: 'NotConfirmed' as ContactStatus
};

