/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmailRecipient } from './emailRecipient';
import { Options } from './options';
import { EmailContent } from './emailContent';


/**
 * Email data
 */
export interface EmailMessageData { 
    /**
     * List of recipients
     */
    Recipients: Array<EmailRecipient>;
    Content: EmailContent;
    Options?: Options;
}

