/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type EmailValidationStatus = 'None' | 'Valid' | 'Unknown' | 'Risky' | 'Invalid';

export const EmailValidationStatus = {
    None: 'None' as EmailValidationStatus,
    Valid: 'Valid' as EmailValidationStatus,
    Unknown: 'Unknown' as EmailValidationStatus,
    Risky: 'Risky' as EmailValidationStatus,
    Invalid: 'Invalid' as EmailValidationStatus
};

