/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BodyPart } from './bodyPart';
import { MessageAttachment } from './messageAttachment';
import { Utm } from './utm';


/**
 * Proper e-mail content
 */
export interface EmailContent { 
    /**
     * List of e-mail body parts, with user-provided MIME types (text/html, text/plain etc)
     */
    Body?: Array<BodyPart>;
    /**
     * A key-value collection of custom merge fields, shared between recipients. Should be used in e-mail body like so: {firstname}, {lastname} etc.
     */
    Merge?: { [key: string]: string; };
    /**
     * Attachments provided by sending binary data
     */
    Attachments?: Array<MessageAttachment>;
    /**
     * A key-value collection of custom e-mail headers.
     */
    Headers?: { [key: string]: string; };
    /**
     * Postback header.
     */
    Postback?: string;
    /**
     * E-mail with an optional name to be used as the envelope from address (e.g.: John Doe <email@domain.com>)
     */
    EnvelopeFrom?: string;
    /**
     * Your e-mail with an optional name (e.g.: John Doe <email@domain.com>)
     */
    From: string;
    /**
     * To what address should the recipients reply to (e.g. John Doe <email@domain.com>)
     */
    ReplyTo?: string;
    /**
     * Default subject of email.
     */
    Subject?: string;
    /**
     * Name of template.
     */
    TemplateName?: string;
    /**
     * Names of previously uploaded files that should be sent as downloadable attachments
     */
    AttachFiles?: Array<string>;
    Utm?: Utm;
}

