/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type EmailPredictedValidationStatus = 'None' | 'Valid' | 'LowRisk' | 'HighRisk' | 'Invalid';

export const EmailPredictedValidationStatus = {
    None: 'None' as EmailPredictedValidationStatus,
    Valid: 'Valid' as EmailPredictedValidationStatus,
    LowRisk: 'LowRisk' as EmailPredictedValidationStatus,
    HighRisk: 'HighRisk' as EmailPredictedValidationStatus,
    Invalid: 'Invalid' as EmailPredictedValidationStatus
};

