/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmailJobFailedStatus { 
    Address?: string;
    Error?: string;
    /**
     * RFC Error code
     */
    ErrorCode?: number;
    Category?: string;
}

