/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * List of recipients
 */
export interface EmailRecipient { 
    /**
     * Proper email address.
     */
    Email: string;
    /**
     * A key-value collection of merge fields which can be used in e-mail body.
     */
    Fields?: { [key: string]: string; };
}

