/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of event
 */
export type EventType = 'Submission' | 'FailedAttempt' | 'Bounce' | 'Sent' | 'Open' | 'Click' | 'Unsubscribe' | 'Complaint';

export const EventType = {
    Submission: 'Submission' as EventType,
    FailedAttempt: 'FailedAttempt' as EventType,
    Bounce: 'Bounce' as EventType,
    Sent: 'Sent' as EventType,
    Open: 'Open' as EventType,
    Click: 'Click' as EventType,
    Unsubscribe: 'Unsubscribe' as EventType,
    Complaint: 'Complaint' as EventType
};

