/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type InboundRouteActionType = 'ForwardToEmail' | 'NotifyViaHttp' | 'Stop';

export const InboundRouteActionType = {
    ForwardToEmail: 'ForwardToEmail' as InboundRouteActionType,
    NotifyViaHttp: 'NotifyViaHttp' as InboundRouteActionType,
    Stop: 'Stop' as InboundRouteActionType
};

