/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type InboundRouteFilterType = 'EmailAddress' | 'Subject';

export const InboundRouteFilterType = {
    EmailAddress: 'EmailAddress' as InboundRouteFilterType,
    Subject: 'Subject' as InboundRouteFilterType
};

