/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MessageAttachment { 
    /**
     * File\'s content as byte array (or a Base64 string)
     */
    BinaryContent: string;
    /**
     * Display name of the file
     */
    Name: string;
    /**
     * MIME content type
     */
    ContentType?: string;
    /**
     * Size of your attachment (in bytes).
     */
    Size?: number;
}

