/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type MessageCategory = 'Unknown' | 'Ignore' | 'Spam' | 'BlackListed' | 'NoMailbox' | 'GreyListed' | 'Throttled' | 'Timeout' | 'ConnectionProblem' | 'SPFProblem' | 'AccountProblem' | 'DNSProblem' | 'NotDeliveredCancelled' | 'CodeError' | 'ManualCancel' | 'ConnectionTerminated' | 'NotDelivered';

export const MessageCategory = {
    Unknown: 'Unknown' as MessageCategory,
    Ignore: 'Ignore' as MessageCategory,
    Spam: 'Spam' as MessageCategory,
    BlackListed: 'BlackListed' as MessageCategory,
    NoMailbox: 'NoMailbox' as MessageCategory,
    GreyListed: 'GreyListed' as MessageCategory,
    Throttled: 'Throttled' as MessageCategory,
    Timeout: 'Timeout' as MessageCategory,
    ConnectionProblem: 'ConnectionProblem' as MessageCategory,
    SpfProblem: 'SPFProblem' as MessageCategory,
    AccountProblem: 'AccountProblem' as MessageCategory,
    DnsProblem: 'DNSProblem' as MessageCategory,
    NotDeliveredCancelled: 'NotDeliveredCancelled' as MessageCategory,
    CodeError: 'CodeError' as MessageCategory,
    ManualCancel: 'ManualCancel' as MessageCategory,
    ConnectionTerminated: 'ConnectionTerminated' as MessageCategory,
    NotDelivered: 'NotDelivered' as MessageCategory
};

