/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EncodingType } from './encodingType';


/**
 * E-mail configuration
 */
export interface Options { 
    /**
     * By how long should an e-mail be delayed (in minutes). Maximum is 35 days.
     */
    TimeOffset?: number | null;
    /**
     * Name of your custom IP Pool to be used in the sending process
     */
    PoolName?: string;
    /**
     * Name of selected channel.
     */
    ChannelName?: string;
    Encoding?: EncodingType;
    /**
     * Should the opens be tracked? If no value has been provided, Account\'s default setting will be used.
     */
    TrackOpens?: boolean | null;
    /**
     * Should the clicks be tracked? If no value has been provided, Account\'s default setting will be used.
     */
    TrackClicks?: boolean | null;
}
export namespace Options {
}


