/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Change the ordering of this inbound route for when matching the inbound
 */
export interface SortOrderItem { 
    /**
     * ID of the route to change the order of
     */
    PublicInboundId: string;
    /**
     * 1 - route will be used first
     */
    SortOrder: number;
}

