/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SplitOptimizationType = 'Opens' | 'Clicks';

export const SplitOptimizationType = {
    Opens: 'Opens' as SplitOptimizationType,
    Clicks: 'Clicks' as SplitOptimizationType
};

