/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SplitOptimizationType } from './splitOptimizationType';


/**
 * Optional A/X split campaign options
 */
export interface SplitOptions { 
    OptimizeFor?: SplitOptimizationType;
    /**
     * For how long should the results be measured until determining the winner template (content)
     */
    OptimizePeriodMinutes?: number;
}
export namespace SplitOptions {
}


