/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A change to SubAccount email credits pool, with an additional note.
 */
export interface SubaccountEmailCreditsPayload { 
    /**
     * Positive or negative value; this will be added or subtracted from Subaccount\'s current email Credits pool.
     */
    Credits: number;
    /**
     * Note to append to this credits change, for history.
     */
    Notes?: string;
}

