/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Settings related to sending emails
 */
export interface SubaccountEmailSettingsPayload { 
    /**
     * True, if Account needs credits to send emails. Otherwise, false
     */
    RequiresEmailCredits?: boolean;
    /**
     * Maximum size of email including attachments in MB\'s
     */
    EmailSizeLimit?: number;
    /**
     * Amount of emails Account can send daily
     */
    DailySendLimit?: number;
    /**
     * Maximum number of contacts the Account can have. 0 means that parent account\'s limit is used.
     */
    MaxContacts?: number;
    /**
     * Can the SubAccount purchase Private IP for themselves
     */
    EnablePrivateIPPurchase?: boolean;
    /**
     * Name of your custom IP Pool to be used in the sending process
     */
    PoolName?: string;
    ValidSenderDomainOnly?: boolean | null;
}

