/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TemplateType = 'RawHTML' | 'DragDropEditor' | 'LandingPageEditor' | 'TemplateEditor' | 'FormTemplate' | 'LandingPageTemplate' | 'PaymentConfirmationTemplate' | 'LandingPageProductTemplate' | 'LandingPageCheckoutTemplate' | 'LandingPagePaymentConfirmationTemplate' | 'LandingPageNewsletterProductTemplate' | 'LandingPageNewsletterPaymentConfirmationTemplate' | 'NewsletterSubscriptionCancellationTemplate';

export const TemplateType = {
    RawHtml: 'RawHTML' as TemplateType,
    DragDropEditor: 'DragDropEditor' as TemplateType,
    LandingPageEditor: 'LandingPageEditor' as TemplateType,
    TemplateEditor: 'TemplateEditor' as TemplateType,
    FormTemplate: 'FormTemplate' as TemplateType,
    LandingPageTemplate: 'LandingPageTemplate' as TemplateType,
    PaymentConfirmationTemplate: 'PaymentConfirmationTemplate' as TemplateType,
    LandingPageProductTemplate: 'LandingPageProductTemplate' as TemplateType,
    LandingPageCheckoutTemplate: 'LandingPageCheckoutTemplate' as TemplateType,
    LandingPagePaymentConfirmationTemplate: 'LandingPagePaymentConfirmationTemplate' as TemplateType,
    LandingPageNewsletterProductTemplate: 'LandingPageNewsletterProductTemplate' as TemplateType,
    LandingPageNewsletterPaymentConfirmationTemplate: 'LandingPageNewsletterPaymentConfirmationTemplate' as TemplateType,
    NewsletterSubscriptionCancellationTemplate: 'NewsletterSubscriptionCancellationTemplate' as TemplateType
};

