/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Visibility of a template
 */
export type TemplateScope = 'Personal' | 'Global';

export const TemplateScope = {
    Personal: 'Personal' as TemplateScope,
    Global: 'Global' as TemplateScope
};

