/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * HTTP or HTTPS Protocal used for link tracking.
 */
export type TrackingType = 'None' | 'Delete' | 'Http' | 'ExternalHttps' | 'InternalCertHttps' | 'LetsEncryptCert';

export const TrackingType = {
    None: 'None' as TrackingType,
    Delete: 'Delete' as TrackingType,
    Http: 'Http' as TrackingType,
    ExternalHttps: 'ExternalHttps' as TrackingType,
    InternalCertHttps: 'InternalCertHttps' as TrackingType,
    LetsEncryptCert: 'LetsEncryptCert' as TrackingType
};

