/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type VerificationStatus = 'Processing' | 'Ready' | 'Expired' | 'Verified' | 'Error';

export const VerificationStatus = {
    Processing: 'Processing' as VerificationStatus,
    Ready: 'Ready' as VerificationStatus,
    Expired: 'Expired' as VerificationStatus,
    Verified: 'Verified' as VerificationStatus,
    Error: 'Error' as VerificationStatus
};

