/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VerificationStatus } from './verificationStatus';
import { FileUploadResult } from './fileUploadResult';


/**
 * Simple verification file result info
 */
export interface VerificationFileResult { 
    /**
     * Identifier of this verification result
     */
    VerificationID?: string;
    /**
     * Origin file name
     */
    Filename?: string;
    VerificationStatus?: VerificationStatus;
    FileUploadResult?: FileUploadResult;
    /**
     * Date of creation in YYYY-MM-DDThh:ii:ss format
     */
    DateAdded?: string;
    /**
     * Origin file extension
     */
    Source?: string;
}
export namespace VerificationFileResult {
}


