/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Update webhook payload
 */
export interface WebhookUpdatePayload { 
    /**
     * Filename
     */
    Name?: string;
    /**
     * URL of notification.
     */
    URL?: string;
    NotifyOncePerEmail?: boolean | null;
    NotificationForSent?: boolean | null;
    NotificationForOpened?: boolean | null;
    NotificationForClicked?: boolean | null;
    NotificationForUnsubscribed?: boolean | null;
    NotificationForAbuseReport?: boolean | null;
    NotificationForError?: boolean | null;
    IsEnabled?: boolean | null;
}

