/**
 * Elastic Email REST API
 *
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Create webhook payload
 */
export interface WebhookCreatePayload { 
    /**
     * Filename
     */
    Name: string;
    /**
     * URL of notification.
     */
    URL: string;
    NotifyOncePerEmail?: boolean;
    NotificationForSent?: boolean;
    NotificationForOpened?: boolean;
    NotificationForClicked?: boolean;
    NotificationForUnsubscribed?: boolean;
    NotificationForAbuseReport?: boolean;
    NotificationForError?: boolean;
}

