/**
 * Elastic Email REST API
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a href=\"https://api.elasticemail.com/public/help\">here</a>.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccessLevel } from './accessLevel';


/**
 * Newly generated SMTP Credentials with Token
 */
export interface NewSmtpCredentials { 
    /**
     * Unique token to be used in the system
     */
    Token?: string;
    /**
     * Access level of this Smtp Credential.
     */
    AccessLevel?: AccessLevel;
    /**
     * Name of the key.
     */
    Name?: string;
    /**
     * Date this SmtpCredential was created.
     */
    DateCreated?: string;
    /**
     * Date this SmtpCredential was last used.
     */
    LastUse?: string | null;
    /**
     * Date this SmtpCredential expires.
     */
    Expires?: string | null;
    /**
     * Which IPs can use this SmtpCredential
     */
    RestrictAccessToIPRange?: Array<string>;
}

