export * from './campaigns.service';
import { CampaignsService } from './campaigns.service';
export * from './contacts.service';
import { ContactsService } from './contacts.service';
export * from './domains.service';
import { DomainsService } from './domains.service';
export * from './emails.service';
import { EmailsService } from './emails.service';
export * from './events.service';
import { EventsService } from './events.service';
export * from './files.service';
import { FilesService } from './files.service';
export * from './inboundRoute.service';
import { InboundRouteService } from './inboundRoute.service';
export * from './lists.service';
import { ListsService } from './lists.service';
export * from './security.service';
import { SecurityService } from './security.service';
export * from './segments.service';
import { SegmentsService } from './segments.service';
export * from './statistics.service';
import { StatisticsService } from './statistics.service';
export * from './subAccounts.service';
import { SubAccountsService } from './subAccounts.service';
export * from './suppressions.service';
import { SuppressionsService } from './suppressions.service';
export * from './templates.service';
import { TemplatesService } from './templates.service';
export * from './verifications.service';
import { VerificationsService } from './verifications.service';
export const APIS = [CampaignsService, ContactsService, DomainsService, EmailsService, EventsService, FilesService, InboundRouteService, ListsService, SecurityService, SegmentsService, StatisticsService, SubAccountsService, SuppressionsService, TemplatesService, VerificationsService];
